export const EMAIL_PATTERN = '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$';
export const PRODUCT_SORT_VALUES = ['ASC Name', 'DESC Name', 'ASC Price', 'DSC Price'];
export const API = 'https://localgoods1.azurewebsites.net/';
export const API_PATH_AUTH = 'api/Auth';
export const PATH_LOGIN = 'Login';
export const PATH_REGISTER = 'Registration';
export const EXPIRE_IN = 1440;
export const REFRESH_EXPIRE_IN = 14400;
export const USER_ROLES = ['seller', 'customer'];
